# Generated by Django 5.1.4 on 2025-01-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
    ]
