# Generated by Django 5.1.4 on 2025-01-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_map_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='pharmacy',
        ),
    ]
